### ISSUE TITLE
Any plans for contribute or white-box patch?

### ISSUE THREAD

**Issue by MapleEve** [Ultimeit/palguard#3]
Hi Ulti
We are a team of multi-dedi server platform and want to merge this dll into win pods and add some other functions, to have the best performance either this AC is a pod service API or use static function to import into the memory than injection. So if it's possibe to contribute like Unofficial-API or provide a PDB to let us contribute/modify this inject?

**Comment by Ultimeit** [comment]
Message me in discord: https://discord.gg/palguard
